### ISSUE TITLE
Auto Report [lithium, snowyleavesplus] (Jul 9, 2024 - 4:18:14 PM)

### ISSUE THREAD

**Issue by cobaltlol2** [Bawnorton/NeruinaAutoReports#101]
## Report:
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-07-09 16:18:14
Description: Ticking BlockState

java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.size()" because "sectionedBlockChangeTrackers" is null
	at me.jellysquid.mods.lithium.common.entity.block_tracking.ChunkSectionChangeCallback.onBlockChange(ChunkSectionChangeCallback.java:57)
	at net.minecraft.class_2826.lithium$trackBlockStateChange(class_2826.java:1640)
	at net.minecraft.class_2826.handler$ela000$lithium$updateFlagCounters(class_2826.java:1612)
	at net.minecraft.class_2826.method_12256(class_2826.java:69)
	at net.minecraft.class_2826.redirect$ehe000$lithium$setBlockStateNoLocking(class_2826.java:1021)
	at net.minecraft.class_2826.method_16675(class_2826.java:59)
	at net.minecraft.class_2818.method_12010(class_2818.java:235)
	at net.minecraft.class_1937.method_30092(class_1937.java:232)
	at net.minecraft.class_1937.method_8652(class_1937.java:217)
	at net.minecraft.class_1937.method_8501(class_1937.java:326)
	at net.minecraft.class_2397.handler$fjh000$snowyleavesplus$randomTickInject(class_2397.java:1088)
	at net.minecraft.class_2397.method_9514(class_2397.java)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:1153)
	at net.minecraft.class_3218.redirect$efm000$lithium$redirectBlockStateTick(class_3218.java:5789)
	at net.minecraft.class_3218.mixinextras$bridge$redirect$efm000$lithium$redirectBlockStateTick$217(class_3218.java)
	at com.bawnorton.neruina.handler.TickHandler.safelyTickBlockState(TickHandler.java:136)
	at net.minecraft.class_3218.wrapOperation$eok000$neruina$catchTickingBlockState$notTheCauseOfTickLag(class_3218.java:9777)
	at net.minecraft.class_3218.method_18203(class_3218.java:519)
	at net.minecraft.class_3215.method_14161(class_3215.java:365)
	at net.minecraft.class_3215.method_12127(class_3215.java:310)
	at net.minecraft.class_3218.method_18765(class_3218.java:350)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at me.jellysquid.mods.lithium.common.entity.block_tracking.ChunkSectionChangeCallback.onBlockChange(ChunkSectionChangeCallback.java:57)

-- Source: Spruce Leaves --
Details:
	Message: Cannot invoke "java.util.ArrayList.size()" because "sectionedBlockChangeTrackers" is null
	Position: class_2339{x=1, y=90, z=-47}
	BlockState: Block{minecraft:spruce_leaves}[distance=1,persistent=false,snowiness=none,waterlogged=false]
Stacktrace:
	at me.jellysquid.mods.lithium.common.entity.block_tracking.ChunkSectionChangeCallback.onBlockChange(ChunkSectionChangeCallback.java:57)
	at net.minecraft.class_2826.lithium$trackBlockStateChange(class_2826.java:1640)
	at net.minecraft.class_2826.handler$ela000$lithium$updateFlagCounters(class_2826.java:1612)
	at net.minecraft.class_2826.method_12256(class_2826.java:69)
	at net.minecraft.class_2826.redirect$ehe000$lithium$setBlockStateNoLocking(class_2826.java:1021)
	at net.minecraft.class_2826.method_16675(class_2826.java:59)
	at net.minecraft.class_2818.method_12010(class_2818.java:235)
	at net.minecraft.class_1937.method_30092(class_1937.java:232)
	at net.minecraft.class_1937.method_8652(class_1937.java:217)
	at net.minecraft.class_1937.method_8501(class_1937.java:326)
	at net.minecraft.class_2397.handler$fjh000$snowyleavesplus$randomTickInject(class_2397.java:1088)
	at net.minecraft.class_2397.method_9514(class_2397.java)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:1153)
	at net.minecraft.class_3218.redirect$efm000$lithium$redirectBlockStateTick(class_3218.java:5789)
	at net.minecraft.class_3218.mixinextras$bridge$redirect$efm000$lithium$redirectBlockStateTick$217(class_3218.java)
	at com.bawnorton.neruina.handler.TickHandler.safelyTickBlockState(TickHandler.java:136)
	at net.minecraft.class_3218.wrapOperation$eok000$neruina$catchTickingBlockState$notTheCauseOfTickLag(class_3218.java:9777)
	at net.minecraft.class_3218.method_18203(class_3218.java:519)
	at net.minecraft.class_3215.method_14161(class_3215.java:365)
	at net.minecraft.class_3215.method_12127(class_3215.java:310)
	at net.minecraft.class_3218.method_18765(class_3218.java:350)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.2, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2359942600 bytes (2250 MiB) / 4093640704 bytes (3904 MiB) up to 6308233216 bytes (6016 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600H with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.99
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5612
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc.
	Graphics card #1 VRAM (MiB): 512.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 27.20.11028.10001
	Memory slot #0 capacity (MiB): 32768.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 36989.32
	Virtual memory used (MiB): 16798.68
	Swap memory total (MiB): 4864.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 127885.68, total: 487109.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 127885.68, total: 487109.00
	Space in storage for io.netty.native.workdir (MiB): available: 127885.68, total: 487109.00
	Space in storage for java.io.tmpdir (MiB): available: 127885.68, total: 487109.00
	Space in storage for workdir (MiB): available: 127885.68, total: 487109.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientenvironment: AmbientEnvironment 17.0.0.5
		amplified_nether: Amplified Nether 1.2.5
		appleskin: AppleSkin 3.0.2+mc1.21
		architectury: Architectury 13.0.3
		axolotlitemfix: Axolotl Item Fix 1.1.9
		badoptimizations: BadOptimizations 2.1.4
		balm-fabric: Balm 21.0.12
			kuma_api: KumaAPI 21.0.4
		betteradvancements: Better Advancements 0.4.2.16
		bettergrass: FabricBetterGrass 1.0.17+1.21
		bettermounthud: Better Mount HUD 1.2.4
		betterpingdisplay: Better Ping Display 1.1.1
		betterthirdperson: Better Third Person 1.9.0
		boatbreakfix: Boat Break Fix 1.0.2
		bobby: Bobby 5.2.3+mc1.21
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.106+1.21
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.106+1.21
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.106+1.21
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.106+1.21
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.106+1.21
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.106+1.21
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.106+1.21
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.106+1.21
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.106+1.21
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.106+1.21
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.106+1.21
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.106+1.21
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.106+1.21
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.106+1.21
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.106+1.21
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.106+1.21
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.106+1.21
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.106+1.21
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.106+1.21
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.106+1.21
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.106+1.21
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cameraoverhaul: Camera Overhaul 1.4.1-fabric-universal
		cardinal-components: Cardinal Components API 6.1.0
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-block: Cardinal Components API (blocks) 6.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
			cardinal-components-item: Cardinal Components API (items) 6.1.0
			cardinal-components-level: Cardinal Components API (world saves) 6.1.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.0
			cardinal-components-world: Cardinal Components API (worlds) 6.1.0
		charm: Charm 7.0.28
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmonium: Charmonium 7.0.0
		chat_heads: Chat Heads 0.12.7
		cicada: CICADA 0.8.1+1.21-and-above
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 18.0.0.1
		completedshieldfix: Walksy's Complete Shield Fixes 1.0.2
		continuity: Continuity 3.0.0-beta.5+1.21
		controlling: Controlling 18.0.1
		creativecore: CreativeCore 2.12.0
			net_neoforged_bus: bus 7.2.0
		creeperoverhaul: Creeper Overhaul 4.0.4
		debugify: Debugify 1.21+1.0
		do_a_barrel_roll: Do a Barrel Roll 3.6.1+1.21
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mixinsquared: MixinSquared 0.1.1
		dynamic_fps: Dynamic FPS 3.6.0
			net_lostluma_battery: battery 1.0.1
		easyanvils: Easy Anvils 21.0.2
		easymagic: Easy Magic 21.0.1
		eatinganimationid: Eating Animation 1.21+1.9.72
		emi: EMI 1.1.10+1.21+fabric
		endrem: End Remastered 5.3.2
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		entity_model_features: Entity Model Features 2.1.3
		entity_sound_features: Entity Sound Features 0.4
		entity_texture_features: Entity Texture Features 6.1.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.6
		fabric-api: Fabric API 0.100.6+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.14+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.17+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.1+86024ea6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.24+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.11+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.2+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.12+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.0+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.12+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.24+6ced4dd9d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.67+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.70+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.4+5a8c785ed1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.5+78017270d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.81+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		fallingleaves: Falling Leaves 1.16.1
		fallingtrees: Falling Trees 0.12.3
		fastipping: Fast IP Ping 1.0.3
		ferritecore: FerriteCore 7.0.0
		firstperson: FirstPerson 2.4.3
		forgeconfigapiport: Forge Config API Port 21.0.1
			com_electronwill_night-config_core: core 3.7.4
			com_electronwill_night-config_toml: toml 3.7.4
		geckoanimfix: GeckoLibIrisCompat 1.0.0
		geckolib: GeckoLib 4 4.5.6
		getittogetherdrops: Get It Together, Drops! fabric-1.21-1.3.1
		glitchcore: GlitchCore 2.0.0.2
			net_jodah_typetools: typetools 0.6.3
		handcrafted: Handcrafted 4.0.1
		immediatelyfast: ImmediatelyFast 1.2.18+1.21
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.34+mc1.21
		inventoryhud: Inventory HUD + ${version}
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemswapper: ItemSwapper 0.7.0
		java: OpenJDK 64-Bit Server VM 21
		kiwi: Kiwi Library 15.1.0+fabric
		languagereload: Language Reload 1.6.1+1.21
		leahs-immersive-thunder: Immersive Thunder 1.21+1.2.2
		libertyvillagers: Liberty's Villagers 1.0.15+fabric+1.21
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
				packet_tweaker: Packet Tweaker 0.5.1+24w03b
		libipn: libIPN 6.0.0
		lithium: Lithium 0.12.7
		lmft: Load My F***ing Tags 1.0.4+1.21
		minecraft: Minecraft 1.21
		modelfix: Model Gap Fix 1.21-1.6
		modmenu: Mod Menu 11.0.1
		morechathistory: More Chat History 1.3.1
		mousetweaks: Mouse Tweaks 2.26
		mr_dynamic_torches: Dynamic Torches 4
		mru: Mineblock's Repeated Utilities 0.4.4+1.21
		necronomicon: Necronomicon 1.4.2
		nerb: Not Enough Recipe Book 0.4
		neruina: Neruina 2.1.0
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.17.0
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.17.0
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.17.0
			org_apache_maven_maven-artifact: maven-artifact 3.8.1
			org_kohsuke_github-api: github-api 1.318
		netherportalfix: NetherPortalFix 21.0.2
		noisium: Noisium 2.2.1+mc1.21
		notenoughanimations: NotEnoughAnimations 1.7.4
		nullscape: Nullscape 1.2.7
		nvidium: Nvidium 0.2.9-beta
		packetfixer: Packet Fixer 1.4.1
		pandalib: PandaLib 0.3
		particlerain: Particle Rain 2.1.1
		pickupnotifier: Pick Up Notifier 21.0.0
		ping-wheel: Ping Wheel 1.9.1
		placeholder-api: Placeholder API 2.4.0+1.21
		presencefootsteps: Presence Footsteps 1.10.0+1.21
			kirin: Kirin UI 1.19.0+1.21
		puzzleslib: Puzzles Lib 21.0.11
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.21
		resourcefulconfig: Resourcefulconfig 3.0.2
		resourcefullib: Resourceful Lib 3.0.9
			com_teamresourceful_bytecodecs: bytecodecs 1.1.2
			com_teamresourceful_yabn: yabn 1.0.3
		resourcepackoverrides: Resource Pack Overrides 21.0.0
		searchables: Searchables 1.0.1
		sereneseasons: SereneSeasons 10.0.0.2
		shulkerboxtooltip: Shulker Box Tooltip 5.0.3+1.21
		skinlayers3d: 3d-Skin-Layers 1.6.6
		smoothgui: SmoothGui 0.1.1
		snowundertrees: Snow Under Trees 2.4.0+1.21
		snowyleavesplus: SnowyLeavesPlus 0.1.12
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.21-1.4.3
		sounds: Sounds 1.0.1+1.21
		sparsestructures: SparseStructures 2.2.0
		spyglass_improvements: Spyglass Improvements 1.5.3
		stitchedsnow: Stiched Snow 1.1.0
		tcdcommons: TCD Commons API 3.12+fabric-1.21
		tectonic: Tectonic 2.4.0
		terrablender: TerraBlender 4.0.0.1
		timm: The Immersive Music Mod 1.0.3
		tool_trims: Tool Trims 2.1.3
		toughasnails: ToughAsNails 10.0.0.5
		visuality: Visuality 0.7.6+1.21
		visualworkbench: Visual Workbench 21.0.1
		weaponmaster_ydm: YDM's Weapon Master 4.2.3
		yeetusexperimentus: Yeetus Experimentus 87.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: (off)
```

**Comment by Wemsur** [comment]
same problem
